#!/usr/bin/env python3

import cake

if __name__ == "__main__":
    conf = cake.ConfigProvider.get_config()
    for tag in conf:
        if conf[tag].get('auto'):
            service = cake.Service(tag)
            if not service.is_running():
                print("Not running, starting:", tag)
                service.start()
            elif not service.is_up_to_date():
                print("Updates, restarting:", tag)
                service.stop()
                service.start()

