#!/usr/bin/env python3

import cake

if __name__ == "__main__":
    conf = cake.Service.read_config()
    for tag in conf.keys():
        if "auto" in conf[tag]:
            service = cake.Service(tag)
            if not service.running():
                print("Not running, starting:", tag)
                service.start()
            elif not service.is_up_to_date():
                print("Updates, restarting:", tag)
                service.stop()
                service.start()

